name: video_ui
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  animated_splash_screen: ^1.0.1+2
  better_player: ^0.0.72
  carousel_slider: ^3.0.0
  cupertino_icons: ^1.0.2
  dio: ^4.0.0
  easy_localization: ^3.0.0
  expansion_tile_card: ^2.0.0
  file_picker: ^3.0.3
  flutter:
    sdk: flutter
  flutter_local_notifications: ^6.0.0
  flutter_screenutil: ^5.0.0+2
  fluttertoast: ^8.0.7
  font_awesome_flutter: ^9.0.0
  google_fonts: ^2.0.0
  hexcolor: 
  http: ^0.13.3
  image_gallery_saver: 
  image_picker: 
  page_transition: ^1.1.7+6
  path: ^1.8.0
  path_provider: ^2.0.2
  permission: 
  permission_handler: 
  provider: ^5.0.0
  screen: 
  share: ^2.0.4
  shared_preferences: ^2.0.6
  theme_provider: ^0.5.0

dev_dependencies:
  flutter_launcher_icons: "0.9.0"
  flutter_native_splash: ^1.1.8+4
  flutter_test:
    sdk: flutter
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/cut.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
  #   - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Graphique
      fonts:
        - asset: assets/fonts/Graphique-W01-Regular.ttf
    - family: Taj
      fonts:
        - asset: assets/fonts/Tajawal-Regular.ttf
    - family: Bebu
      fonts:
        - asset: assets/fonts/BebasNeue-Regular.ttf
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
    - family: Sans
      fonts:
        - asset: assets/fonts/OpenSans-Regular.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
